### ISSUE TITLE
Bug in Date columns, it gets offset by 1 day

### ISSUE THREAD

**Issue by nsingla** [quantopian/qgrid#83] opened 2016-06-09 04:50 UTC
http://nbviewer.jupyter.org/gist/TimShawver/b4bc80d1128407c56c9a

Just compare the Date column/index for the dataframe and qgrid. For some reason it gets offset by 1 day which is wrong.

**Comment by TimShawver** [comment] 2016-06-20 19:02
This is fixed on master, so if you install with `git clone https://github.com/quantopian/qgrid.git` you should get the fix.  This was caused by some bad handling of timezone information in the javascript which displays dates.  Here's the fix: https://github.com/quantopian/qgrid/commit/73eaa7adf1762f66eaf4d30ed9cbf385a7e9d9fa#diff-136e6e8c0bd6577a27ec9ea081c23f9aR224

I'll close it once we release this fix to pypi.

**Closed** 2017-09-05 01:33 UTC
