### ISSUE TITLE
Toolbar functions issues

### ISSUE THREAD

**Issue by wagger301** [quantopian/qgrid#110] opened 2017-04-19 17:46 UTC
Having issues with export and add row when using in jupyter notebook. I was following the example: 
`from pandas_datareader import wb
df2 = wb.download(indicator='NY.GDP.PCAP.KD', country=['all'], start=2005, end=2008)
df2.columns = ['GDP per capita (constant 2005 US$)']
qgrid.show_grid(df2, show_toolbar=True)`

and got the error "Cannot add a row to a table with a non-integer index" for adding a row. 
And when trying to export it just copies the table and reproduces it below.

Thanks

**Comment by TimShawver** [comment] 2017-06-12 05:40
Thanks for the report.  That's actually the expected behavior for the export button currently.  When you export the notebook by using the Download as Html feature on the File menu, or by rendering it on NbViewer, the 2nd copy will be visible and the first will be gone.  Admittedly this is a weird user experience and I'm in the process of making this widget behave more like a standard widget, since the notebook now supports exporting standard widgets to static views in this way.  So I'm hoping that user experience will improve soon.

As for the add row issue, that's an issue I've know about for a while and I actually mentioned in the docs here: http://qgrid.readthedocs.io/en/latest/#qgrid.show_grid
```
Adding/removing rows is an experimental feature which only works with DataFrames that have an integer index. 
```
I think it's unlikely I'll fix that anytime soon since it's fairly low priority.

**Comment by TimShawver** [comment] 2017-10-16 15:47
The export button is gone in qgrid 1.0 and it's no longer possible to export a fully functional version of qgrid to static html, because in the new version of qgrid the sorting/filtering logic is done on the server.  That being said, you should still be able to export a partially functional version of qgrid where sorting/filtering is broken (and only 200 rows are included) once https://github.com/jupyter-widgets/ipywidgets/issues/1597 is fixed.

I realize that's probably not all that useful to people so another alternative that might be a better option is to use the new "binder" service for rendering live notebooks.  I'm using it to host the demo notebook for qgrid and it's been great so far: https://beta.mybinder.org/v2/gh/quantopian/qgrid-notebooks/master?filepath=index.ipynb

I'm going to close this since I no longer plan to provide full support for static html exporting, and I think "binder" will be a suitable alternative for a lot of users.

**Closed by TimShawver** 2017-10-16 15:47 UTC
Labels: enhancement
