### ISSUE TITLE
disable sorting / filtering

### ISSUE THREAD

**Issue by sergun** [quantopian/qgrid#164] opened 2018-01-21 19:28 UTC
Hello,

is it possible to disable sorting / filtering on entire table / column?

Thanks!
Sergey.

**Comment by TimShawver** [comment] 2018-01-21 19:53
I looked around a bit and couldn't find any way of doing that currently, sorry.  Does seem like something worth adding though, and not too much work. I'll mark it as an enhancement and keep it in mind for future releases.

**Comment by cdknorow** [comment] 2018-01-27 23:44
I'd also like this, I want to use qgrid to display some results in a table to a user. But I have limited space and the filter tab is cutting off the words. It would also be nice to be able to rename index to rank.

**Comment by TimShawver** [comment] 2018-01-28 13:43
@cdknorow thanks...should be easy to add an option for hiding the filters.

Regarding renaming the index column, you can already do this by modifying your DataFrame before rendering qgrid:
```
df.index.names = ['rank']
qgrid.show_grid(df)
```

**Comment by cdknorow** [comment] 2018-01-28 21:51
@TimShawver after renaming the index qgrid is still displaying the index column as index.

-Chris

**Comment by TimShawver** [comment] 2018-01-29 01:40
@cdknorow oh weird, it worked for me when I tried it. Could you provide code that reproduces the issue? There must be something different about the DataFrame I tested with I guess...

**Comment by TimShawver** [comment] 2018-01-29 05:11
@cdknorow @sergun regarding disabling sorting/filtering...

I'm putting together a minor release and included the ability to disable sorting and/or filtering on the entire table.  I haven't added the ability to disable on a per-column basis yet though.

The new options are available as part of the `grid_options` dictionary, so they can be set in the normal way:

```
# all grids
qgrid.set_grid_option('sortable', False)
qgrid.set_grid_option('filterable', False)

# Or for a single grid
qgrid.show_grid(df_types, grid_options={'sortable': False, 'filterable': False})

```

You can try this out in the latest beta on pypi (currently 1.0.1 beta 1).  Install it with `pip install qgrid --pre`.  The rest of the installation steps are the same.  It's not available on conda yet.

Could you let me know if you have a chance to try it out? I'm hoping to get some more testing on the new beta so it'd be helpful to know if it worked. Thanks.

**Comment by cdknorow** [comment] 2018-02-01 05:19
Thanks I'll try this out asap.

**Comment by TimShawver** [comment] 2018-02-19 04:39
This enhancement was included in version 1.0.1 which has now been released. I'll leave this open since I've only partially addressed it...disabling sorting/filtering on a per column basis is not yet implemented.

**Comment by TimShawver** [comment] 2018-07-11 06:36
Closing because disabling sorting/filtering on a per column basis is now possible as of version 1.1.0.

**Closed by TimShawver** 2018-07-11 06:36 UTC
Labels: enhancement

**Comment by CarlosGrohmann** [comment] 2022-07-04 17:38
Sorry if I'm late to the party, but I'm setting a notebook on Colab for a research project using qgrid. From the code, I can see that one can set the grid to be "filterable" or not, but not specific columns. Sorting is something possible to enable/diable on a per column basis, but filtering is not. In my case, I'd like the user to be able to filter by some columns (qualitative values) but not by other columns (quantitative). 
Thanks
