### ISSUE TITLE
Pandas 1.0.1 Compatibility

### ISSUE THREAD

**Issue by andrewpritchett** [quantopian/qgrid#294] opened 2020-02-18 16:40 UTC
### Environment

* Operating System:
* Python Version: `Python 3.7.6`
* How did you install Qgrid: `/opt/conda/bin/pip install qgrid`
* Python packages: `pandas==1.0.1, notebook==6.0.3, qgrid==1.2.0`
* Jupyter lab packages (if applicable): 

### Description of Issue

* What did you expect to happen? Display Qgrid
* What happened instead? `AttributeError: module 'pandas.core' has no attribute 'index'`

### Reproduction Steps

1. Generate df: `test_df = pd.DataFrame([{'a': 1, 'b': 2, 'c': 3}, {'a': 4, 'b': 5, 'c': 6}, {'a': 10, 'b': 20, 'c': 30}, {'a': 40, 'b': 50, 'c': 60}])`
2. Show qgrid: `qgrid.show_grid(test_df)`

### What steps have you taken to resolve this already?

None, yet.

### Anything else?

...

**Comment by gerrymanoim** [comment] 2020-02-18 16:49
Dupe of https://github.com/quantopian/qgrid/issues/287

**Closed by gerrymanoim** 2020-02-18 16:49 UTC
