### ISSUE TITLE
qgrid stopped working on new jupyter lab version 1.0.0

### ISSUE THREAD

**Issue by people-can-fly** [quantopian/qgrid#264] opened 2019-07-17 14:37 UTC
### Environment

* Operating System:
* Python Version: `3.7.0`
* How did you install Qgrid: (`pip`)
* Python packages: `
qgrid==1.1.1
notebook==6.0.0
jupyterlab==1.0.2`

* Jupyter lab packages (if applicable): `JupyterLab v1.0.2
Known labextensions:
   app dir: C:\Users\ahossain_exd\AppData\Roaming\Python\share\jupyter\lab
        @jupyter-widgets/jupyterlab-manager v1.0.1 enabled  ok
        @jupyterlab/toc v1.0.1 enabled  ok
        @krassowski/jupyterlab_go_to_definition v0.6.1 enabled  ok
        @mohirio/jupyterlab-horizon-theme v1.0.2 enabled  ok
        @oriolmirosa/jupyterlab_materialdarker v0.4.0 enabled  ok
        @ryantam626/jupyterlab_code_formatter v0.3.0 enabled  ok
        qgrid v1.1.1 enabled  ok`

### Description of Issue

* What did you expect to happen?
Show qgrid
* What happened instead?
Error displaying widget: model not found
### Reproduction Steps

1.df = pd.DataFrame({"a": [1, 2, 3, 4], "b": [5, 6, 7, 8]})
2.qgrid.show_grid(df)
...

**Comment by EricCacciavillani** [comment] 2019-07-18 15:01
Having the same problem here too...

**Comment by ankostis** [comment] 2019-07-21 16:16
Dupe of #261.

**Comment by tkrabel** [comment] 2019-12-04 19:47
Currently, the qgrid extension is incompatible with jupyter lab 1.0 or higher. I have created a JS package that fixes the issue. You can install a working qgrid JS extension for qgrid 1.1.1 now the following way:

    jupyter labextension @8080labs/qgrid

[![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/tkrabel/qgrid_jupyterlab/master?urlpath=lab/tree/qgrid_demo.ipynb)

You can find a binder demo repo here: [https://github.com/tkrabel/qgrid_jupyterlab](https://github.com/tkrabel/qgrid_jupyterlab)

**Comment by gerrymanoim** [comment] 2019-12-31 17:53
Fixed in https://github.com/quantopian/qgrid/pull/275

**Closed by gerrymanoim** 2019-12-31 17:53 UTC
