### ISSUE TITLE
ipywidgets stop working after enabling qgrid

### ISSUE THREAD

**Issue by parente** [quantopian/qgrid#165] opened 2018-01-22 03:51 UTC
### Environment

* Operating System: OSX
* Python Version: 3.6
* How did you install Qgrid: pip
* Python packages: notebook 5.2.2, jupyterlab 0.31.0, qgrid 1.0.0, ipywidgets 7.1.0
* Jupyter lab packages (if applicable): @jupyter-widgets/jupyterlab-manager v0.33.0, qgrid v1.0.0

### Description of Issue

ipywidgets fail to render in JupyterLab after installing/enabling the qgrid Lab extension.

### Reproduction Steps

1. Open a notebook in jupyterlab.
2. `import qgrid; qgrid.show_grid(a_df)`
3. Grid appears (but with some errors in the JS console)
4. `import ipywidgets; ipywidgets.Button(description="test")`
5. "Error displaying widget` appears in the notebook
6. Stop lab, run `jupyter labextension disable qgrid`, restart lab
7. Try the ipywidgets test again
8. Button appears as expected

### What steps have you taken to resolve this already?

> Please Note: Jupyterlab support has been tested with jupyterlab 0.30.5 and jupyterlab-manager 0.31.3, so if you're having trouble, try installing those versions. Feel free to file an issue if you find that qgrid isn't working with a newer version of either dependency.

I can fallback on older versions of lab and widgets-manager. I'm opening this ticket to raise awareness about a likely problem with the latest versions.

**Comment by TimShawver** [comment] 2018-01-22 05:05
Thanks, it looks like this is the same problem that's described in https://github.com/quantopian/qgrid/issues/154.  I didn't realize it broke all ipywidgets though so that's good to know...it makes the need for a new release more urgent, so I'll probably make the new release in the next day or two.

As described in that issue, the problem should be fixed in a new pre-release version I've posted to pypi.  You can install this as follows:
```
pip install qgrid==1.0.1b0
jupyter labextension install qgrid@1.0.1-beta.0
```

**Comment by parente** [comment] 2018-01-22 13:55
Indeed it's the same problem. I didn't equate the title on that one as being the same issue, but in retrospect, I should have.

Good to hear a new release is on its way. Thanks for continuing to work on qgrid!

**Comment by dhirschfeld** [comment] 2018-01-29 08:42
Is it necessary to always specify the version ?
```
jupyter labextension install qgrid@1.0.1-beta.0
```


Would leaving it off not pick up the latest?
```
jupyter labextension install qgrid
```

**Comment by TimShawver** [comment] 2018-02-04 15:23
@dhirschfeld it's necessary for pre-releases, and `1.0.1-beta.0` is a pre-release.  If you leave it off, and installed a pre-release with pip, you'll see an error about version mismatch between the python code and the js code. It won't be necessary going forward once this beta is officially released (which I'm hoping to do today once I look into https://github.com/quantopian/qgrid/issues/167).

**Comment by TimShawver** [comment] 2018-02-19 04:27
This is fixed in version 1.0.1 which has now been released. Thanks again for reporting this and feel free to reopen if the fix doesn't work for you.

**Closed by TimShawver** 2018-02-19 04:27 UTC
Labels: duplicate

**Comment by TimShawver** [comment] 2018-02-23 15:52
Are you getting that for Qgrid, your other widgets, or both? That message can be shown for reasons other than this bug, such as if you have not yet run the Jupyterlab-specific installation steps:
```
jupyter labextension install @jupyter-widgets/jupyterlab-manager
jupyter labextension install qgrid
```

**Comment by sterlinm** [comment] 2018-02-23 19:18
I think the issue is Qgrid specifically rather than all widgets. A simple widget using interact seems to work okay.

![screen shot 2018-02-23 at 2 16 43 pm](https://user-images.githubusercontent.com/1461273/36612360-679ccc06-18a4-11e8-855e-42b176dbcfdd.png)

**Comment by dhirschfeld** [comment] 2018-02-23 23:35
I don't believe nteract properly supports widgets yet:
nteract/nteract#1385

**Comment by sterlinm** [comment] 2018-02-24 00:00
I meant the interact function from ipywidgets, not nteract. I'm using JupyterLab.
