### ISSUE TITLE
Is it possible to set qgrid as the default dataframe renderer?

### ISSUE THREAD

**Issue by shuvrobiswas** [quantopian/qgrid#106] opened 2017-02-14 21:32 UTC
Hi quantopian,

Thanks for this excellent package!

I am wondering, is it possible to make qgrid the default renderer for dataframes, so that I can simply type

`df`

shift+enter and see a qgrid (without the need to import qgrid, or use any additional syntax)?

This would be very useful in terms of adopting qgrid for all of my projects.

Best,
Shuvro

**Comment by lengau** [comment] 2017-03-02 17:36
DISCLAIMER: I'm not a qgrid developer, just a user.

This would probably require merging qgrid into pandas, since Jupyter notebook gets the HTML used for displaying the DataFrame by running its `_repr_html_` method, so it's unlikely to happen any time soon.

**Comment by ssanderson** [comment] 2017-03-02 17:42
Closing this as a dupe of https://github.com/quantopian/qgrid/issues/8.  From the discussion there, I believe this is already possible (and in fact the IPython team did some work to make this possible specifically for QGrid).  @ellisonbg made an example notebook for this at https://gist.github.com/ellisonbg/5c54f995bfcd64b90dc2, though it's a year old now and a lot has changed in that time, so I'm not 100% sure it still works.

**Closed by ssanderson** 2017-03-02 17:42 UTC
