### ISSUE TITLE
working on jupyter but not jupyterhub

### ISSUE THREAD

**Issue by sektionschef** [quantopian/qgrid#85] opened 2016-07-01 13:27 UTC
I love the idea of sorting and filtering my dataframes in the notebooks directly. i tried to install qgrid on my local and on a remote system on jupyterhub. without success. 

**what i did**
I did `pip3 install qgrid` and after importing qgrid I tried a `qgrid.show_grid(df)` right away. no success, no output.
so i additionally ran: `qgrid.nbinstall(overwrite=True)`  i read about in the demo.

**symptoms are**
- it can't access the css and js files: https://blabla.com/hub/nbextensions/qgridjs/lib/slick.grid.css Failed to load resource: the server responded with a status of 404 (Not Found) in the chrome console and I receive a 404 in the logfiles of jupyterhub for those files:
- if i use jupyter notebook with `jupyter notebook` instead of jupyterhub on my local system it works and everything is loaded correctly
- if i use jupyterhub and start `show_grid` with `show_toolbar=True` parameter and click on Export. qgrid is loaded all of a sudden and everything is loaded.

any idea where i can look into? thanks

**Comment by Lefort-Antoine** [comment] 2016-07-29 12:30
I have the exactly same issue. 

Functions call by clicking on "Export" toolbar are : _display_html_ and _display_javascript_ 
while show_grid call function _display_

any idea ? thanks

**Comment by TimShawver** [comment] 2016-12-27 05:47
Thanks for the detailed report.  I haven't tried qgrid with jupyterhub yet, but based on what I'm reading online, it seems widgets that work with jupyter notebook should also work on jupyterhub.  Did you happen to try any other widgets to see if you could get them working? If other widgets are working and qgrid is the only widget that's not then there's probably a bug I need to fix.

If you're not able to get widgets working with jupyterhub at all, this thread might be helpful: https://groups.google.com/forum/#!topic/jupyter/n-GI5uNuHNU

**Comment by lengau** [comment] 2017-03-02 17:39
I suspect that @rushtehrani is correct. This is happening for us on multiple JupyterHub servers and it only affects qgrid.

**Comment by stvogel** [comment] 2017-03-16 10:57
I got exactly the same problem when running with jupyterhub.
All other widgets are working. And I definitely have the same python running.

Is there a workaround to correct the url-path?  It sounds easy to fix, but I don't know where to do that.

**Comment by TimShawver** [comment] 2017-06-12 06:06
Thanks for all the info.  I was able to reproduce this, and I'm working on a fix for it.  I don't have a quick fix in mind but I have another larger project in progress that I know will fix it.  Basically I'm going to update the packaging/deployment so that it behaves just like other widgets, which will also make it work in jupyterhub. 

In the meantime you can get around this issue by setting the `remote_js` option to `True` before attempting to call `show_grid` in your notebook.  If you've already called `show_grid` with `remote_js` set to it's default value of false, you may need to clear all cell output and refresh the page (using your browser's refresh button) for this workaround to take effect.  

Since you'll always want `remote_js` to be `True`, the easiest way to do this is probably to execute  `qgrid.set_defaults(remote_js=True)` in any notebook in which you want to use qgrid.  You can also pass this option into the `show_grid` function itself, as described in the docs here: http://qgrid.readthedocs.io/en/latest/#qgrid.show_grid

**Comment by stvogel** [comment] 2017-06-12 06:51
Great! This worked for me. Thanks.

**Comment by JohnOmernik** [comment] 2017-07-03 18:18
I am (I think( running into this issue. I am running Jupyter via Jupyter hub and I all I get when I do show grid is a little X where the widgets go.  I tried the remote_js and it's still not working here... where should I look for logs that can help me troubleshoot? My jupyter notebook server doesn't having any glaring entries that concern me...

**Comment by TimShawver** [comment] 2017-07-05 14:56
@JohnOmernik if you open up your browser's developer tools (on Chrome and OS X it's under View -> Developer -> Developer Tools) and then click on the Console tab you might see some errors there that could help us diagnose the issue.

**Comment by JohnOmernik** [comment] 2017-07-05 15:56
So I see a request for 

https://jupyterhub-mainhub-prod.marathon.slave.mesos:22443/hub/nbextensions/qgridjs/lib/slick.grid.css 

Which I get a 302 found with a location of /hub/nbextensions/qgridjs/lib/slick.grid.css

Which then I get a not found (404) request for: https://jupyterhub-mainhub-prod.marathon.slave.mesos:22443/hub/nbextensions/qgridjs/lib/slick.grid.css 404

(Also for qgrid.css) Does that help?

**Comment by TimShawver** [comment] 2017-07-05 16:56
Yea that's helpful.  It seems like the `remote_js=True` setting has not taken effect in your notebook.   I would expect qgrid to be attempting to load those css files from `https://cdn.rawgit.com/quantopian/qgrid/` if `remote_js=True` was working.  I think maybe what's happening is you have another cell in your notebook where rendering qgrid failed, and the output from that cell is saved with your notebook.  To clear that cell output, and make sure it's javascript doesn't run again you can try the following steps: 

1.  In the notebook menu, clear all cell output:
![screen shot 2017-07-05 at 12 23 17 pm](https://user-images.githubusercontent.com/5055866/27874241-d918c428-617c-11e7-9df7-64c972846fab.png)
2. Save the notebook (with all your cell output cleared).
2. Click the refresh button on your browser to refresh the page.
3. Before attempting to call `qgrid.show_grid`, execute a cell with `qgrid.set_defaults(remote_js=True)`
4. Now try and render your qgrid with a call to `show_grid` or by constructing a `QGridWidget` directly and displaying it.

If that doesn't work it might be that your browser is doing some aggressive caching so you might try disabling caching in your browser temporarily while you're going through these steps.  Normally the way I do this is by enabling `Disable cache (while DevTools is open)` in the settings for Chrome's dev tools, and then leaving the dev tools panel open while I'm troubleshooting.

**Comment by JohnOmernik** [comment] 2017-07-05 17:17
Ok, walking through all of that got working.  So for Jupyterhub, the trick is to use remote_js=True (and ensure things aren't cached).

**Comment by TimShawver** [comment] 2017-07-05 17:51
Yea that's the situation for now.  The next release I'm working on will eliminate the need for this workaround.

**Comment by hbensalem** [comment] 2017-09-12 15:54
Hi, 
I have the same problem with JupyterHub. No errors but the grid doesn't show.
Unfortunqtely using qgrid.set_defaults(remote_js=True) did not solve the problem. Any other suggestions ?
Thanks !

**Comment by TimShawver** [comment] 2017-09-18 16:00
@hbensalem I just discovered that qgrid is not working with ipywidgets 7.x (it only works with 6.x).  I have a new branch of qgrid that will work with 7.x, and I'll likely merge it soon in light of this discovery.

Could you check your version of ipywidgets, and if it's 7, try using 6 instead if possible?

**Comment by TimShawver** [comment] 2017-10-16 17:56
This is fixed in qgrid 1.0, which is currently available in beta form.  See the installation instructions on the [updated readme page](https://github.com/quantopian/qgrid#installation).

To use qgrid with Jupyterhub, simply install it according to the installation instructions on the readme in the same environment where you're running Jupyterhub. The special steps I've listed above should now be unnecessary.

**Closed by TimShawver** 2017-10-16 17:56 UTC
