### ISSUE TITLE
Tests failing: `iNaT` no longer in `pandas.tslib`

### ISSUE THREAD

**Issue by toddrme2178** [quantopian/qgrid#136] opened 2017-10-20 21:09 UTC
The tests are failing with pandas 0.20.3:

```
======================================================================
ERROR: pd_json (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: pd_json
Traceback (most recent call last):
  File "/usr/lib64/python3.6/unittest/loader.py", line 153, in loadTestsFromName
    module = __import__(module_name)
  File "/home/abuild/rpmbuild/BUILD/qgrid-1.0.0b7/qgrid/pd_json/__init__.py", line 1, in <module>
    from .json import to_json, read_json, loads, dumps  # noqa
  File "/home/abuild/rpmbuild/BUILD/qgrid-1.0.0b7/qgrid/pd_json/json.py", line 6, in <module>
    from pandas.tslib import iNaT
ImportError: cannot import name 'iNaT'


======================================================================
ERROR: qgrid.pd_json (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: qgrid.pd_json
Traceback (most recent call last):
  File "/usr/lib64/python3.6/unittest/loader.py", line 462, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/lib64/python3.6/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/home/abuild/rpmbuild/BUILD/qgrid-1.0.0b7/qgrid/pd_json/__init__.py", line 1, in <module>
    from .json import to_json, read_json, loads, dumps  # noqa
  File "/home/abuild/rpmbuild/BUILD/qgrid-1.0.0b7/qgrid/pd_json/json.py", line 6, in <module>
    from pandas.tslib import iNaT
ImportError: cannot import name 'iNaT'
```

 It appears that `iNaT` is not available in `pandas.tslib`, and `pandas.tslib` itself is deprecated.

**Comment by TimShawver** [comment] 2017-11-07 18:39
Thanks for the heads up...I'll look into this for the next beta.

**Comment by TimShawver** [comment] 2017-11-10 18:48
Hmm I haven't been able to reproduce this...the expected behavior is that the if statement here:  https://github.com/quantopian/qgrid/blob/master/qgrid/grid.py#L14 would prevent anything in the `qgrid/pd_json` folder from being imported, so I'm not sure why that's happening when you run the tests.

Are you using pytest to run the tests? That's the intended method of running the tests.  If you don't have pytest installed, you can install it with `pip install -U pytest`.  Run the tests with `pytest`, or run a specific test like so: `pytest qgrid/tests/test_grid.py::test_series_of_text_filters`. All tests are passing on my machine with pandas 0.20.3 installed:
```
(qgrid) tim:~/repo/qgrid-old (fix-beta-7) $ pytest
=========================================== test session starts ===========================================
platform darwin -- Python 3.6.1, pytest-3.2.3, py-1.4.34, pluggy-0.4.0
rootdir: /Users/tshawver/repo/qgrid-old, inifile:
collected 7 items                                                                                          

qgrid/tests/test_grid.py .......

======================================== 7 passed in 5.69 seconds =========================================```

**Comment by toddrme2178** [comment] 2017-11-14 14:22
I was using `setup.py test`.  But trying to use pytest I notice the test
files aren't included in the source archive so I can't tell if the problem
would persist under pytest.

On Nov 10, 2017 13:48, "Tim Shawver" <notifications@github.com> wrote:

Hmm I haven't been able to reproduce this...the expected behavior is that
the if statement here: https://github.com/quantopian/
qgrid/blob/master/qgrid/grid.py#L14 would prevent anything in the
qgrid/pd_json folder from being imported, so I'm not sure why that's
happening when you run the tests.

Are you using pytest to run the tests? That's the intended method of
running the tests. If you don't have pytest installed, you can install it
with pip install -U pytest. Run the tests with pytest, or run a specific
test like so: pytest qgrid/tests/test_grid.py::test_series_of_text_filters.
All tests are passing on my machine with pandas 0.20.3 installed:

(qgrid) tim:~/repo/qgrid-old (fix-beta-7) $ pytest
=========================================== test session starts
===========================================
platform darwin -- Python 3.6.1, pytest-3.2.3, py-1.4.34, pluggy-0.4.0
rootdir: /Users/tshawver/repo/qgrid-old, inifile:
collected 7 items

qgrid/tests/test_grid.py .......

======================================== 7 passed in 5.69 seconds
=========================================```

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/quantopian/qgrid/issues/136#issuecomment-343554848>,
or mute
the thread

**Comment by TimShawver** [comment] 2017-11-15 00:58
Ah ok...yea the tests aren't included with the pypi or conda packages. You have to clone the repo from github and run `pytest` from the root folder of the repository to run the tests.

**Comment by TimShawver** [comment] 2017-11-20 03:52
Closing as this is the expected behavior for tests.

**Closed by TimShawver** 2017-11-20 03:52 UTC
Labels: cleanup, next release
