### ISSUE TITLE
NotImplementedError: orient='table' is not supported for MultiIndex

### ISSUE THREAD

**Issue by djinnome** [quantopian/qgrid#192] opened 2018-05-07 22:55 UTC
### Environment

* Operating System: Mac OS X 10.12.7
* Python Version: `$ python --version` . Python 3.6.1 :: Anaconda custom (x86_64)
* How did you install Qgrid: (`pip`, `conda`, or `other (please explain)`) . conda
* Python packages: `$ pip freeze` or `$ conda list` (please include qgrid, notebook, and jupyterlab versions) See below. It is very long.
* Jupyter lab packages (if applicable): `$ jupyter labextension list` . Doesn't work on JupyterLab. Trying on Jupyter notebook does work.

### Description of Issue

* What did you expect to happen?  output a qgrid:

<table border="1" class="dataframe">\n  <thead>\n    <tr>\n      <th></th>\n      <th>carbon source</th>\n      <th colspan="7" halign="left">glucose</th>\n      <th colspan="7" halign="left">citric acid</th>\n      <th colspan="7" halign="left">malic acid</th>\n    </tr>\n    <tr>\n      <th></th>\n      <th>genotype</th>\n      <th>wild-type</th>\n      <th>GDH1</th>\n      <th>GND1</th>\n      <th>IDP1</th>\n      <th>MAE1</th>\n      <th>ZWF1</th>\n      <th>pos5</th>\n      <th>wild-type</th>\n      <th>GDH1</th>\n      <th>GND1</th>\n      <th>IDP1</th>\n      <th>MAE1</th>\n      <th>ZWF1</th>\n      <th>pos5</th>\n      <th>wild-type</th>\n      <th>GDH1</th>\n      <th>GND1</th>\n      <th>IDP1</th>\n      <th>MAE1</th>\n      <th>ZWF1</th>\n      <th>pos5</th>\n    </tr>\n    <tr>\n      <th>RxnId</th>\n      <th>RxnName</th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>xAMINOACID</th>\n      <th>Amino acid composition</th>\n      <td>0.000</td>\n      <td>0.000</td>\n      <td>0.000</td>\n      <td>0.000</td>\n      <td>0.000</td>\n      <td>0.000</td>\n      <td>0.000</td>\n      <td>0.000</td>\n      <td>-0.000</td>\n      <td>0.000</td>\n      <td>-0.000</td>\n      <td>-0.000</td>\n      <td>-0.000</td>\n      <td>-0.000</td>\n      <td>0.000</td>\n      <td>0.000</td>\n      <td>-0.000</td>\n      <td>-0.000</td>\n      <td>-0.000</td>\n      <td>-0.000</td>\n      <td>-0.000</td>\n    </tr>\n    <tr>\n      <th>xBIOMASS</th>\n      <th>Biomass production</th>\n      <td>0.000</td>\n      <td>0.000</td>\n      <td>0.000</td>\n      <td>-0.000</td>\n      <td>0.000</td>\n      <td>0.000</td>\n      <td>0.000</td>\n      <td>0.000</td>\n      <td>0.000</td>\n      <td>0.000</td>\n      <td>0.000</td>\n      <td>-0.000</td>\n      <td>0.000</td>\n      <td>0.000</td>\n      <td>-0.000</td>\n      <td>0.000</td>\n      <td>0.000</td>\n      <td>0.000</td>\n      <td>0.000</td>\n      <td>0.000</td>\n      <td>0.000</td>\n    </tr>\n    <tr>\n      <th>xLIPID</th>\n      <th>Lipids pool</th>\n      <td>0.000</td>\n      <td>-0.000</td>\n      <td>0.000</td>\n      <td>0.000</td>\n      <td>0.000</td>\n      <td>0.000</td>\n      <td>0.000</td>\n      <td>-0.000</td>\n      <td>0.000</td>\n      <td>0.000</td>\n      <td>-0.000</td>\n      <td>-0.000</td>\n      <td>0.000</td>\n      <td>0.000</td>\n      <td>-0.000</td>\n      <td>-0.000</td>\n      <td>-0.000</td>\n      <td>-0.000</td>\n      <td>0.000</td>\n      <td>-0.000</td>\n      <td>-0.000</td>\n    </tr>\n    <tr>\n      <th>xMAINTENANCE</th>\n      <th>Non-growth associated maintenance (NGAM)</th>\n      <td>-0.014</td>\n      <td>-0.018</td>\n      <td>-0.014</td>\n      <td>-0.014</td>\n      <td>-0.014</td>\n      <td>-0.014</td>\n      <td>-0.014</td>\n      <td>-0.006</td>\n      <td>-0.006</td>\n      <td>-0.006</td>\n      <td>-0.006</td>\n      <td>-0.006</td>\n      <td>-0.006</td>\n      <td>-0.006</td>\n      <td>-0.006</td>\n      <td>-0.006</td>\n      <td>-0.006</td>\n      <td>-0.006</td>\n      <td>-0.006</td>\n      <td>-0.006</td>\n      <td>-0.006</td>\n    </tr>\n    <tr>\n      <th>xPOOL_AC_EM</th>\n      <th>Acyl-CoAs pool</th>\n      <td>0.000</td>\n      <td>-0.000</td>\n      <td>-0.000</td>\n      <td>-0.000</td>\n      <td>0.000</td>\n      <td>0.000</td>\n      <td>0.000</td>\n      <td>-0.000</td>\n      <td>0.000</td>\n      <td>-0.000</td>\n      <td>0.000</td>\n      <td>0.000</td>\n      <td>-0.000</td>\n      <td>-0.000</td>\n      <td>0.000</td>\n      <td>-0.000</td>\n      <td>0.000</td>\n      <td>-0.000</td>\n      <td>0.000</td>\n      <td>0.000</td>\n      <td>0.000</td>\n    </tr>\n  </tbody>\n</table>

* What actually happend:  `NotImplementedError: orient='table' is not supported for MultiIndex`

### Reproduction Steps

1.  `qgrid.show_grid(df)`
2.
3.
...

### Anything else?

Here is the output of `conda list`

```
conda list
# packages in environment at /Users/zuck016/.pyenv/versions/anaconda3-4.4.0:
#
# Name                    Version                   Build  Channel
_license                  1.1                      py36_1  
absl-py                   0.2.0                     <pip>
alabaster                 0.7.10                   py36_0  
altair                    2.0.0rc1                  <pip>
ampl-mp                   3.1.0                         0    conda-forge
anaconda                  custom                   py36_0  
anaconda-client           1.6.3                    py36_0  
anaconda-navigator        1.6.2                    py36_0  
anaconda-project          0.6.0                    py36_0  
antimony                  2.8.1                         0    sys-bio
anyqt                     0.0.8                    py36_1    conda-forge
appdirs                   1.4.3                    py36_0    conda-forge
appnope                   0.1.0                    py36_0  
appscript                 1.0.1                    py36_0  
argcomplete               1.8.2                    py36_0    conda-forge
argh                      0.26.2                   py36_1    conda-forge
arrow                     0.10.0                    <pip>
asn1crypto                0.22.0                   py36_0  
astor                     0.6.2                     <pip>
astroid                   1.4.9                    py36_0  
astropy                   1.3.3               np111py36_0  
attrs                     17.4.0                    <pip>
babel                     2.4.0                    py36_0  
backports                 1.0                      py36_0  
beautifulsoup4            4.6.0                    py36_0  
binaryornot               0.4.4                     <pip>
bioconductor-annotationdbi 1.38.0                 r3.3.2_0    bioconda
bioconductor-annotationhub 2.6.0                  r3.3.2_0    bioconda
bioconductor-biobase      2.34.0                 r3.3.2_0    bioconda
bioconductor-biocgenerics 0.20.0                 r3.3.2_0    bioconda
bioconductor-biocinstaller 1.24.0                 r3.3.2_0    bioconda
bioconductor-biocparallel 1.6.6                  r3.3.2_1    bioconda
bioconductor-biomart      2.28.0                 r3.3.2_0    bioconda
bioconductor-biostrings   2.42.1                 r3.3.2_0    bioconda
bioconductor-biovizbase   1.20.0                 r3.3.2_0    bioconda
bioconductor-bsgenome     1.42.0                 r3.3.2_0    bioconda
bioconductor-ensembldb    1.6.2                  r3.3.2_0    bioconda
bioconductor-genomeinfodb 1.10.3                 r3.3.2_0    bioconda
bioconductor-genomicalignments 1.10.0                 r3.3.2_0    bioconda
bioconductor-genomicfeatures 1.26.4                 r3.3.2_0    bioconda
bioconductor-genomicranges 1.26.4                 r3.3.2_0    bioconda
bioconductor-ggbio        1.22.0                 r3.3.2_0    bioconda
bioconductor-graph        1.50.0                 r3.3.2_1    bioconda
bioconductor-interactivedisplaybase 1.12.0                 r3.3.2_0    bioconda
bioconductor-iranges      2.8.2                  r3.3.2_0    bioconda
bioconductor-organismdbi  1.14.1                 r3.3.2_0    bioconda
bioconductor-rbgl         1.48.1                 r3.3.2_1    bioconda
bioconductor-rsamtools    1.26.1                 r3.3.2_0    bioconda
bioconductor-rtracklayer  1.34.2                 r3.3.2_1    bioconda
bioconductor-s4vectors    0.12.2                 r3.3.2_0    bioconda
bioconductor-summarizedexperiment 1.4.0                  r3.3.2_2    bioconda
bioconductor-variantannotation 1.20.3                 r3.3.2_0    bioconda
bioconductor-xvector      0.14.1                 r3.3.2_0    bioconda
bioconductor-zlibbioc     1.20.0                 r3.3.2_1    bioconda
biopython                 1.70                np111py36_0    conda-forge
bioservices               1.4.16                   py36_1    bioconda
bitarray                  0.8.1                    py36_0  
blas                      1.1                    openblas    conda-forge
blaze                     0.10.1                   py36_0  
bleach                    1.5.0                     <pip>
bleach                    1.5.0                    py36_0  
bokeh                     0.12.5                   py36_1  
boost                     1.56.0                   py36_3    rdkit
boto                      2.46.1                   py36_0  
bottleneck                1.2.1               np111py36_0  
brewer2mpl                1.4.1                     <pip>
bwa                       0.7.15                        1    bioconda
bzip2                     1.0.6                         3  
ca-certificates           2018.4.16                     0    conda-forge
cairo                     1.14.8                        0  
casadi                    3.3.0           py36_blas_openblas_0  [blas_openblas]  conda-forge
certifi                   2018.1.18                 <pip>
certifi                   2018.4.16                py36_0    conda-forge
cffi                      1.10.0                   py36_0  
chardet                   3.0.3                    py36_0  
chardet                   3.0.4                     <pip>
cite2c                    0.2.1                     <pip>
click                     6.7                      py36_0  
click-configfile          0.2.2                     <pip>
cloudpickle               0.4.0                     <pip>
cloudpickle               0.2.2                    py36_0  
clyent                    1.2.2                    py36_0  
cobra                     0.11.2                    <pip>
cobrame                   0.0.7                     <pip>
colorama                  0.3.9                    py36_0  
commonmark                0.7.5                      py_0    conda-forge
conda                     4.5.2                    py36_0    conda-forge
conda-build               3.0.8                    py36_0  
conda-env                 2.6.0                         0    conda-forge
conda-verify              2.0.0                    py36_0  
configparser              3.5.0                     <pip>
contextlib2               0.5.5                    py36_0  
cookiecutter              1.5.1                     <pip>
cryptography              1.8.1                    py36_0  
csscompressor             0.9.4                     <pip>
curl                      7.52.1                        0  
CVXcanon                  0.1.1                     <pip>
cvxpy                     0.4.11                    <pip>
cycler                    0.10.0                   py36_0  
cython                    0.25.2                   py36_0  
cytoolz                   0.8.2                    py36_0  
d3flux                    0.1.4                     <pip>
dask                      0.15.1                    <pip>
dask                      0.14.3                   py36_1  
datashape                 0.5.4                    py36_0  
decorator                 4.0.11                   py36_0  
decorator                 4.2.1                     <pip>
dill                      0.2.7.1                   <pip>
dill                      0.2.7.1                  py36_0    conda-forge
distributed               1.16.3                   py36_0  
docutils                  0.13.1                   py36_0  
easydev                   0.9.35                   py36_0    conda-forge
ECOLIme                   0.0.7                     <pip>
ecos                      2.0.5                     <pip>
entrypoints               0.2.2                    py36_1  
entrypoints               0.2.3                     <pip>
Escher                    1.6.0                     <pip>
et_xmlfile                1.0.1                    py36_0  
ete3                      3.1.1                     <pip>
fastcache                 1.0.2                    py36_1  
filelock                  2.0.7                    py36_0  
fisher                    0.1.5                     <pip>
flask                     0.12.2                   py36_0  
flask-cors                3.0.2                    py36_0  
fontconfig                2.12.1                        3  
freetype                  2.5.5                         2  
funcsigs                  1.0.2                     <pip>
future                    0.16.0                    <pip>
future                    0.16.0                   py36_0    conda-forge
gast                      0.2.0                     <pip>
get_terminal_size         1.0.0                    py36_0  
gettext                   0.19.8.1                      0    conda-forge
gevent                    1.2.1                    py36_0  
gffutils                  0.9                      py36_0    bioconda
ggplot                    0.11.5                    <pip>
gitdb2                    2.0.2                     <pip>
GitPython                 2.1.5                     <pip>
glib                      2.50.2                        1  
glob2                     0.5                      py36_0  
goatools                  0.7.11                    <pip>
greenlet                  0.4.12                   py36_0  
grequests                 0.3.0                    py36_0    conda-forge
grpcio                    1.11.0                    <pip>
gsl                       2.2.1           blas_openblas_3  [blas_openblas]  conda-forge
gurobi                    7.5.1                    py36_0    gurobi
h5py                      2.7.0               np111py36_0  
harfbuzz                  0.9.39                        2  
hdf5                      1.8.17                        1  
heapdict                  1.0.0                    py36_1  
html5lib                  0.9999999                 <pip>
html5lib                  0.999                    py36_0  
humann2                   0.11.1                    <pip>
icu                       54.1                          0  
idna                      2.6                       <pip>
idna                      2.5                      py36_0  
imagesize                 0.7.1                    py36_0  
ipopt                     3.12.8          blas_openblas_0  [blas_openblas]  conda-forge
ipykernel                 4.8.2                     <pip>
ipykernel                 4.6.1                    py36_0  
ipython                   6.1.0                    py36_0  
ipython                   6.1.0                     <pip>
ipython                   6.2.1                     <pip>
ipython_genutils          0.2.0                    py36_0  
ipywidgets                7.2.1                    py36_1    conda-forge
isort                     4.2.5                    py36_0  
itsdangerous              0.24                     py36_0  
jbig                      2.1                           0  
jdcal                     1.3                      py36_0  
jedi                      0.10.2                   py36_2  
jedi                      0.11.1                    <pip>
Jinja2                    2.10                      <pip>
jinja2                    2.9.6                    py36_0  
jinja2-ospath             0.2.1                     <pip>
jinja2-time               0.2.0                     <pip>
joblib                    0.11                     py36_0    conda-forge
joblib                    0.11                      <pip>
jpeg                      9b                            0  
jsonschema                2.6.0                    py36_0  
jupyter                   1.0.0                    py36_3  
jupyter-client            5.2.3                     <pip>
jupyter-contrib-core      0.3.1                     <pip>
jupyter-contrib-nbextensions 0.2.8                     <pip>
jupyter-core              4.4.0                     <pip>
jupyter-highlight-selected-word 0.0.11                    <pip>
jupyter-latex-envs        1.3.8.4                   <pip>
jupyter-nbextensions-configurator 0.2.5                     <pip>
jupyter-tensorboard       0.1.6                     <pip>
jupyter_client            5.0.1                    py36_0  
jupyter_console           5.1.0                    py36_0  
jupyter_core              4.3.0                    py36_0  
jupyterlab                0.31.12                   <pip>
jupyterlab-discovery      4.0.0                     <pip>
jupyterlab-github         0.5.0                     <pip>
jupyterlab-iframe         0.0.2                     <pip>
jupyterlab-latex          0.2.1                     <pip>
jupyterlab-launcher       0.10.5                    <pip>
keyring                   12.0.1                   py36_0    conda-forge
keyrings.alt              3.0                      py36_0    conda-forge
kitchen                   1.2.5                     <pip>
knowledgelab              0.0.1                     <pip>
labkey                    0.6.0                     <pip>
lazy-object-proxy         1.2.2                    py36_0  
lftc                      1.0                       <pip>
libffi                    3.2.1                         1    bioconda
libgcc                    4.8.5                         1  
libgfortran               3.0.0                         0    conda-forge
libiconv                  1.14                          0  
libpng                    1.6.27                        0  
libsedml                  0.4.1                         0    sys-bio
libtiff                   4.0.6                         3  
libxml2                   2.9.4                         0  
libxslt                   1.1.29                        0  
llvmlite                  0.18.0                   py36_0  
locket                    0.2.0                    py36_1  
lxml                      3.7.3                    py36_0  
Markdown                  2.6.11                    <pip>
MarkupSafe                1.0                       <pip>
markupsafe                0.23                     py36_2  
matplotlib                2.0.2               np111py36_0  
matplotlib                2.1.2                     <pip>
matplotlib-venn           0.11.5                    <pip>
memote                    0.2.3                     <pip>
mentos                    0.5                       <pip>
metis                     5.1.0                         3    conda-forge
mistune                   0.8.3                     <pip>
mistune                   0.7.4                    py36_0  
mkl                       2017.0.1                      0  
mkl-service               1.1.2                    py36_3  
mmtf-python               1.0.7                    py36_0    conda-forge
mpi                       1.0                       mpich    conda-forge
mpich                     3.2.1                         0    conda-forge
mpmath                    0.19                     py36_1  
mpmath                    1.0.0                     <pip>
msgpack-python            0.4.8                    py36_0  
multipledispatch          0.4.9                    py36_0  
multiprocess              0.70.5                    <pip>
mumps                     5.0.2           blas_openblas_205  [blas_openblas]  conda-forge
natsort                   5.1.1                     <pip>
navigator-updater         0.1.0                    py36_0  
nbconvert                 5.1.1                    py36_0  
nbconvert                 5.3.1                     <pip>
nbextensions              0.0.6                     <pip>
nbformat                  4.3.0                    py36_0  
nbformat                  4.4.0                     <pip>
nbsetuptools              0.1.4                     <pip>
ncurses                   5.9                          10    conda-forge
networkx                  1.11                     py36_0  
nltk                      3.2.3                    py36_0  
nose                      1.3.7                    py36_1  
notebook                  5.4.1                     <pip>
notebook                  5.0.0                    py36_0  
numba                     0.33.0              np111py36_0  
numexpr                   2.6.2               np111py36_0  
numpy                     1.14.0                    <pip>
numpy                     1.11.3          py36_blas_openblas_202  [blas_openblas]  conda-forge
numpydoc                  0.6.0                    py36_0  
odfpy                     1.3.6                     <pip>
odo                       0.5.0                    py36_1  
olefile                   0.44                     py36_0  
openblas                  0.2.19                        2    conda-forge
openpyxl                  2.4.7                    py36_0  
openssl                   1.0.2o                        0    conda-forge
optlang                   1.3.0                     <pip>
orange3                   3.13.0                   py36_0    conda-forge
packaging                 16.8                     py36_0  
pandas                    0.22.0                    <pip>
pandas                    0.20.1              np111py36_0  
pandocfilters             1.4.2                     <pip>
pandocfilters             1.4.1                    py36_0  
pango                     1.40.3                        1  
parso                     0.1.1                     <pip>
partd                     0.3.8                    py36_0  
path.py                   10.3.1                   py36_0  
pathlib2                  2.2.1                    py36_0  
patsy                     0.4.1                    py36_0  
pcre                      8.39                          0    conda-forge
pep8                      1.7.0                    py36_0  
pexpect                   4.4.0                     <pip>
pexpect                   4.2.1                    py36_0  
phrasedml                 1.0.3                         0    sys-bio
pickleshare               0.7.4                    py36_0  
pillow                    4.1.1                    py36_0  
pip                       9.0.1                    py36_1  
pip                       10.0.1                    <pip>
pixman                    0.34.0                        0  
pkginfo                   1.4.1                    py36_0  
plotly                    2.0.14                    <pip>
pluggy                    0.6.0                     <pip>
ply                       3.10                     py36_0  
poyo                      0.4.1                     <pip>
prompt-toolkit            1.0.15                    <pip>
prompt_toolkit            1.0.14                   py36_0  
protobuf                  3.5.2.post1               <pip>
psutil                    5.4.3                     <pip>
psutil                    5.2.2                    py36_0  
ptscotch                  6.0.4                         5    conda-forge
ptyprocess                0.5.1                    py36_0  
ptyprocess                0.5.2                     <pip>
PuLP                      1.6.8                     <pip>
py                        1.4.33                   py36_0  
py                        1.5.2                     <pip>
pycosat                   0.6.3                    py36_0    conda-forge
pycparser                 2.17                     py36_0  
pycrypto                  2.6.1                    py36_6  
pycurl                    7.43.0                   py36_2  
pyfaidx                   0.5.0                    py36_0    bioconda
pyfasta                   0.5.2                     <pip>
pyflakes                  1.5.0                    py36_0  
pygments                  2.2.0                    py36_0  
pylint                    1.6.4                    py36_1  
pymatbridge               0.6.dev0                  <pip>
pymc3                     3.3                       <pip>
pyodbc                    4.0.16                   py36_0  
pyopenssl                 17.0.0                   py36_0  
pyparsing                 2.2.0                     <pip>
pyparsing                 2.1.4                    py36_0  
pyqt                      5.6.0                    py36_1  
pyqtgraph                 0.10.0                   py36_2    conda-forge
pytables                  3.3.0               np111py36_0  
pytest                    3.0.7                    py36_0  
pytest                    3.4.0                     <pip>
python                    3.6.1                         2  
python-dateutil           2.6.0                    py36_0  
python-dateutil           2.7.2                     <pip>
python-libsbml            5.16.0                    <pip>
python-libsbml            5.16.0           py36h22bb0b1_0    SBMLTeam
python.app                1.2                      py36_0    conda-forge
pytz                      2018.3                    <pip>
pytz                      2017.2                   py36_0  
pywavelets                0.5.2               np111py36_0  
pyyaml                    3.12                     py36_0  
pyzmq                     17.0.0                    <pip>
pyzmq                     16.0.2                   py36_0  
qgrid                     1.0.2                    py36_1    conda-forge
qt                        5.6.2                         2  
qtawesome                 0.4.4                    py36_0  
qtconsole                 4.3.0                    py36_0  
qtpy                      1.2.1                    py36_0  
r-acepack                 1.4.1                  r3.3.2_0    r
r-assertthat              0.1                    r3.3.2_4    r
r-base                    3.3.2                         1    r
r-bh                      1.62.0_1               r3.3.2_0    r
r-bitops                  1.0_6                  r3.3.2_2    r
r-cluster                 2.0.5                  r3.3.2_0    r
r-colorspace              1.3_1                  r3.3.2_0    r
r-curl                    2.3                    r3.3.2_0    r
r-data.table              1.10.0                 r3.3.2_0    r
r-dbi                     0.5_1                  r3.3.2_0    r
r-dichromat               2.0_0                  r3.3.2_2    r
r-digest                  0.6.10                 r3.3.2_0    r
r-evaluate                0.10                   r3.3.2_0    r
r-foreign                 0.8_67                 r3.3.2_0    r
r-formula                 1.2_1                  r3.3.2_0    r
r-futile.logger           1.4.1                  r3.3.2_0    bioconda
r-futile.options          1.0.0                  r3.3.2_0    bioconda
r-ggally                  1.3.0                  r3.3.2_0    bioconda
r-ggplot2                 2.2.0                  r3.3.2_0    r
r-gridextra               2.2.1                  r3.3.2_0    r
r-gtable                  0.2.0                  r3.3.2_0    r
r-highr                   0.6                    r3.3.2_0    r
r-hmisc                   4.0_0                  r3.3.2_0    r
r-htmltable               1.7                    r3.3.2_0    r
r-htmltools               0.3.5                  r3.3.2_0    r
r-httpuv                  1.3.3                  r3.3.2_0    r
r-httr                    1.2.1                  r3.3.2_0    r
r-jsonlite                1.1                    r3.3.2_0    r
r-knitr                   1.15.1                 r3.3.2_0    r
r-labeling                0.3                    r3.3.2_2    r
r-lambda.r                1.1.7                  r3.3.2_0    bioconda
r-lattice                 0.20_34                r3.3.2_0    r
r-latticeextra            0.6_28                 r3.3.2_0    r
r-lazyeval                0.2.0                  r3.3.2_0    r
r-magrittr                1.5                    r3.3.2_2    r
r-markdown                0.7.7                  r3.3.2_2    r
r-mass                    7.3_45                 r3.3.2_0    r
r-matrix                  1.2_7.1                r3.3.2_0    r
r-memoise                 1.0.0                  r3.3.2_0    r
r-mime                    0.5                    r3.3.2_0    r
r-munsell                 0.4.3                  r3.3.2_0    r
r-nnet                    7.3_12                 r3.3.2_0    r
r-openssl                 0.9.5                  r3.3.2_0    r
r-plogr                   0.1_1                  r3.3.2_0    r
r-plyr                    1.8.4                  r3.3.2_0    r
r-prettyunits             1.0.2                  r3.3.2_0    bioconda
r-progress                1.0.2                  r3.3.2_0    bioconda
r-r6                      2.2.0                  r3.3.2_0    r
r-rcolorbrewer            1.1_2                  r3.3.2_3    r
r-rcpp                    0.12.8                 r3.3.2_0    r
r-rcurl                   1.95_4.8               r3.3.2_0    r
r-reshape                 0.8.6                  r3.3.2_0    r
r-reshape2                1.4.2                  r3.3.2_0    r
r-rpart                   4.1_10                 r3.3.2_0    r
r-rsqlite                 1.1_1                  r3.3.2_0    r
r-scales                  0.4.1                  r3.3.2_0    r
r-shiny                   0.14.2                 r3.3.2_0    r
r-snow                    0.4_1                  r3.3.2_0    bioconda
r-sourcetools             0.1.5                  r3.3.2_0    r
r-stringi                 1.1.2                  r3.3.2_0    r
r-stringr                 1.1.0                  r3.3.2_0    r
r-survival                2.40_1                 r3.3.2_0    r
r-tibble                  1.2                    r3.3.2_0    r
r-viridis                 0.3.4                  r3.3.2_0    r
r-xml                     3.98_1.5               r3.3.2_0    r
r-xtable                  1.8_2                  r3.3.2_0    r
r-yaml                    2.1.14                 r3.3.2_0    r
rauth                     0.7.3                     <pip>
rdkit                     2017.03.3           np111py36_1    rdkit
readline                  6.2                           2  
reportlab                 3.4.0                    py36_0  
requests                  2.14.2                   py36_0  
requests                  2.18.4                    <pip>
requests-cache            0.4.10                   py36_0    bioconda
rise                      5.0.0                    py36_0    damianavila82
roadrunner                1.4.8                         0    sys-bio
rope                      0.9.4                    py36_1  
ruamel.yaml               0.14.12                   <pip>
ruamel_yaml               0.11.14                  py36_1  
scalapack                 2.0.2                         0    conda-forge
scikit-image              0.13.0              np111py36_0  
scikit-learn              0.19.1          py36_blas_openblas_200  [blas_openblas]  conda-forge
scikit-learn              0.19.1                    <pip>
scipy                     1.0.0                     <pip>
scipy                     0.19.1          py36_blas_openblas_202  [blas_openblas]  conda-forge
scotch                    6.0.4                         4    conda-forge
scs                       2.0.2                     <pip>
seaborn                   0.7.1                    py36_0  
seaborn                   0.8.1                     <pip>
Send2Trash                1.5.0                     <pip>
serverfiles               0.2.1                      py_0    conda-forge
setuptools                39.0.1                   py36_0    conda-forge
setuptools                39.0.1                    <pip>
simplegeneric             0.8.1                    py36_1  
simplejson                3.8.1                    py36_0    bioconda
singledispatch            3.4.0.3                  py36_0  
sip                       4.18                     py36_0  
six                       1.10.0                   py36_0  
six                       1.11.0                    <pip>
smmap2                    2.0.3                     <pip>
snowballstemmer           1.2.1                    py36_0  
soplex                    0.0.5                     <pip>
sortedcollections         0.5.3                    py36_0  
sortedcontainers          1.5.7                    py36_0  
sphinx                    1.5.6                    py36_0  
spyder                    3.1.4                    py36_0  
sqlalchemy                1.1.9                    py36_0  
sqlite                    3.13.0                        0  
statsmodels               0.8.0               np111py36_0  
suds-jurko                0.6                      py36_1    bioconda
svgutils                  0.3.0                     <pip>
swiglpk                   1.4.4                     <pip>
sympy                     1.0                      py36_0  
sympy                     1.1.1                     <pip>
tablib                    0.12.1                    <pip>
tabulate                  0.8.2                     <pip>
tblib                     1.3.2                    py36_0  
tellurium                 1.3.4                         0    sys-bio
tensorboard               1.7.0                     <pip>
tensorflow-tensorboard    1.5.1                     <pip>
termcolor                 1.1.0                     <pip>
terminado                 0.8.1                     <pip>
terminado                 0.6                      py36_0  
testpath                  0.3                      py36_0  
testpath                  0.3.1                     <pip>
Theano                    1.0.1                     <pip>
tk                        8.5.18                        0  
toolz                     0.8.2                    py36_0  
toolz                     0.9.0                     <pip>
tornado                   5.0.1                     <pip>
tornado                   4.5.1                    py36_0  
tqdm                      4.19.6                    <pip>
traitlets                 4.3.2                    py36_0  
unicodecsv                0.14.1                   py36_0  
unixodbc                  2.3.4                         0  
urllib3                   1.22                      <pip>
vega-datasets             0.4.1                     <pip>
Wand                      0.4.4                     <pip>
wcwidth                   0.1.7                    py36_0  
webencodings              0.5.1                     <pip>
werkzeug                  0.12.2                   py36_0  
wget                      3.2                       <pip>
wheel                     0.29.0                   py36_0  
whichcraft                0.4.1                     <pip>
widgetsnbextension        3.2.1                    py36_0    conda-forge
wrapt                     1.10.10                  py36_0  
xlrd                      1.0.0                    py36_0  
xlrd                      1.1.0                     <pip>
XlsxWriter                1.0.2                     <pip>
xlsxwriter                0.9.6                    py36_0  
xlwings                   0.10.4                   py36_0  
xlwt                      1.2.0                    py36_0  
xz                        5.2.2                         1  
yaml                      0.1.6                         0  
zict                      0.1.2                    py36_0  
zlib                      1.2.8                         3  
```

**Comment by TimShawver** [comment] 2018-06-09 18:58
Interesting...I'm going to try this out today.  I would expect MultiIndexed Dataframes to work (but qgrid just doesn't look "grouped") but maybe this is a case I haven't tried before.  If you have code which creates a sample DataFrame to reproduce this that would be helpful.  Otherwise I can probably figure it out.

**Comment by TimShawver** [comment] 2018-06-09 21:00
I was able to reproduce it, no need for the code sample, thanks.  Seems that the method that qgrid uses in pandas to serialize dataframes to json does not support DataFrames where the `columns` axis is set to a MultiIndex (see https://github.com/pandas-dev/pandas/issues/15996).  A DataFrame with it's `index` set to a MultiIndex works as expected in qgrid (although the display could be improved because the grid doesn't look "grouped") 

Flattening the columns as described [here](https://github.com/quantopian/qgrid/issues/18#issuecomment-149321165) is still the best workaround.  I have some ideas of how to fix this in qgrid but I'm not sure when I'll get to it...there are some other smaller projects that I think provide better ROI (since this seems like it will require a significant change).

I'm going to close this as a duplicate of https://github.com/quantopian/qgrid/issues/18 but thanks for bringing it to my attention.

**Closed by TimShawver** 2018-06-09 21:00 UTC
Labels: duplicate
