### ISSUE TITLE
Columns stacked and unreadable

### ISSUE THREAD

**Issue by rd5802** [quantopian/qgrid#185] opened 2018-04-17 08:58 UTC
### Environment

* Operating System: RHEL
* Python Version: `$ python --version` 3.6
* How did you install Qgrid: (`pip`, `conda`, or `other (please explain)`) pip install
* Python packages: `$ pip freeze` or `$ conda list` (please include qgrid, notebook, and jupyterlab versions)
[LibraryList.txt](https://github.com/quantopian/qgrid/files/1918787/LibraryList.txt)

* Jupyter lab packages (if applicable): `$ jupyter labextension list`

### Description of Issue
Hi,
I`m loading a dataframe into qgrid:

`qgrid_widget = qgrid.QgridWidget(df=dfCRD)`
`qgrid_widget`

dfCRD has 24 columns which are stacked and unreadable.

* What did you expect to happen?

Wanted columns to have  widths allowing to see the names. Thus qgrid should be scrollable horizonally. 

* What happened instead?
dfCRD has 24 columns which are stacked and unreadable.
### Reproduction Steps

1.
Clean Jupytelab notebook

2.
Loading dfCRD dataframe with cx_oracle
3.
`qgrid_widget = qgrid.QgridWidget(df=dfCRD)`
`qgrid_widget`

### What steps have you taken to resolve this already?

`qgrid_widget = qgrid.QgridWidget(df=dfCRD, show_toolbar=True, options={'forceFitColumns': False, 'defaultColumnWidth': 200
})`
`qgrid_widget`

The result is the same.

**Comment by leongn** [comment] 2018-04-25 12:30
I'm experiencing the same problem. The columns are all squashed together (29 columns in my case) and Ican't resize them in my normal notebook view (probably minimum column width reached). 
When I maximize the widget I'm able to resize a column manually but the rest of the columns get squashed together even more. 

There doesn't seem to be an option for horizontal scrolling when the total column widths exceed the screen width.

**Comment by TimShawver** [comment] 2018-04-25 13:58
Did you try setting the `forceFitColumns` and `defaultColumnWidth` grid_options? See the following example from the sample notebook:
```
q_scale = qgrid.show_grid(df_scale, grid_options={'forceFitColumns': False, 'defaultColumnWidth': 200})
```

If you tried that and it didn't work....is this in Jupyterlab? What version of Jupyterlab? Also what browser are you using? Just trying to gather information that might help me reproduce it because I've never seen behavior like this before. Also if you could provide a screenshot, that might be helpful.

**Comment by leongn** [comment] 2018-04-25 14:53
I just realized where the problem originated from: I was using the `QgridWidget` method with the `forceFitColumns` and  `defaultColumnWidth ` options (just like @rd5802 above). When I switched to the `show_grid` method including the grid options, the grid rendered properly without column width problems. 
Thank you!

**Comment by TimShawver** [comment] 2018-04-25 15:11
Ohhh thanks I didn't notice that.  Closing since that will almost certainly fix @rd5802's problem as well.

**Closed by TimShawver** 2018-04-25 15:11 UTC
